import Nav from '@/components/Navbar/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { ThemeContextProvider } from '@/context/ThemeContext'
import ThemeProvider from '@/Provider/ThemeProvider'
import AuthProvider from '@/Provider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <ThemeContextProvider>
        <ThemeProvider>
    <div className='container'>

   
    <div className='wrapper'>

   <Nav/>
        
        {children}
        <Footer/>
        </div>
        </div>
        </ThemeProvider>
        </ThemeContextProvider>
        </AuthProvider>
        </body>
       
    </html>
  )
}
